### ISSUE TITLE
sudoers file needed

### ISSUE THREAD

**Issue by florusboth** [liepumartins/netdata-unbound#1]
Hi, thanks for this plugin! Just what I needed.

I had to create a sudo file for netdata user though:
cat /etc/sudoers.d/netdata 
netdata ALL = NOPASSWD: /usr/sbin/unbound-control

as running this as the netdata user
/usr/libexec/netdata/plugins.d/python.d.plugin debug 1 unbound
gave the sudo password prompt.

Not sure this is the right way to solve it but now the plugin works for me

BR

/florus

**Comment by liepumartins** [comment]
Thank you!
